swagger: "2.0"
info:
  title: Reading Service API
  description: Manages user's library
  version: 0.0.1
host: localhost
schemes:
  - https
produces:
  - application/vnd.blinkbox.books.v2+json
paths:
  /my/library:
    get:
      parameters:
        - name: compact
          in: query
          description: If set, the endpoint returns a minimal representation of user's library.
          required: false
          type: boolean
        - name: count
          in: query
          description: size of the page
          required: false
          type: integer
          format: int32
        - name: offset
          in: query
          description: starting position
          required: false
          type: integer
          format: int32
        - name: owned
          in: query
          description: A flag to state that we only want owned books
          required: false
          type: boolean
        - name: archived
          in: query
          description: A flag to state that we only want archived books
          required: false
          type: boolean
      summary: User's library
      description: The library endpoint returns information about user's library. The response includes all user's books and bookmarks that are not archived.
      responses:
        200:
          description: A map of library items
          schema:
            $ref: Books
    post:
          parameters:
            - name: isbn
              in: body
              description: ISBN
              required: true
              type: string
          description: Add book sample to the library
          responses:
            200:
              description: The book is already in the library
            201:
              description: The book was added to the library
            404:
              description: The book does not exist
    patch:
      parameters:
        - name: isbn
          in: body
          description: ISBN
          required: true
          type: string
        - name: archived
          in: body
          required: true
          schema:
            type: boolean
      description: Archive/Unarchive the book
      responses:
        200:
          description: Book was successfully archived/unarchived
        404:
          description: Library does not have the specified book
  /my/library/{isbn}:
    get:
      parameters:
        - name: isbn
          in: path
          description: ISBN
          required: true
          type: string
      description: Returns book details
      responses:
        200:
          description: Book details
          schema:
            type: object
            $ref: Book
        404:
         description: The book is not in the library
definitions:
  Books:
    properties:
      items:
        type: object
        additionalProperties:
          title: Books in the library
          schema:
            $ref: Book
  Book:
    description: A book
    oneOf:
      - type: object
        description: A minimal representation of a book
        required:
          - isbn
          - title
          - sortableTitle
          - bookType
          - archived
          - readingStatus
          - readingPosition
          - coverUrl
          - addedTime
          - version
        additionalProperties: false
        properties:
          isbn:
            type: string
            description: ISBN
            # required: true
          title:
            type: string
            description: The full title of the book
          sortableTitle:
            type: string
            description: The non-displayable sortable title of the book used for sorting books only
          bookType:
            description: indicates whether the library contains only the sample of the book
            enum:
              -sample
              -full
            # required: true
          archived:
            type: boolean
            description: indicates whether the book is archived
            # required: true
          readingStatus:
            enum:
              - NOTSTARTED
              - READING
              - FINISHED
            # required: true
          readingPosition:
            description: The cfi and percentage of the reading position
            type:
              $ref: ReadingPosition
          coverUrl:
            type: string
            description: The url for the image displayed in a user's library
          addedTime:
            type: datetime
            description: The date and time the book was added to the user's library
          version:
            type: string
            description: The version of the epub
      - type: object
        description: Full representation of a book
        properties:
          isbn:
            type: string
            description: ISBN
            # required: true
          title:
            type: string
            description: The full title of the book
          sortableTitle:
            type: string
            description: The non-displayable sortable title of the book used for sorting books only
          bookType:
            description: indicates whether the library contains only the sample of the book
            enum:
              -sample
              -full
            # required: true
          archived:
            type: boolean
            description: indicates whether the book is archived
            # required: true
          readingStatus:
            enum:
              - NOTSTARTED
              - READING
              - FINISHED
            # required: true
          readingPosition:
            description: The cfi and percentage of the reading position
            type:
              $ref: ReadingPosition
          coverUrl:
            type: string
            description: The url for the image displayed in a user's library
          addedTime:
            type: datetime
            description: The date and time the book was added to the user's library
          version:
            type: string
            description: The version of the epub
          bookmarks:
            description: Map[bookmark_type, [Bookmark]]
            type: object
            additionalProperties:
              title: Bookmarks
              type: array
              items: Bookmark
            # required: true
          links:
            type: object
            additionalProperties:
              title: Links to related resources
              schema:
                $ref: Link
            # required: true
  Bookmark:
    description: Bookmark representation
    properties:
      guid:
        type: string
      cfi:
        type: string
      name:
        type: string
        # required: false
      preview:
        type: string
        # required: false
  ReadingPosition:
    description: Current reading postion
    type: object
    properties:
      cfi:
        type: string
      percentage:
        type: integer
        format: int32
  Link:
    description: Resource link
    properties:
      url:
        type: string
        description: The URL of the resource
    additionalProperties:
      title:
        type: string